# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pitam/Dropbox/COUPP60/AutoBub2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pitam/Dropbox/COUPP60/AutoBub2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/COUPP60/AutoBub2/CMakeFiles /home/pitam/Dropbox/COUPP60/AutoBub2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/COUPP60/AutoBub2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abub

# Build rule for target.
abub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abub
.PHONY : abub

# fast build rule for target.
abub/fast:
	$(MAKE) -f CMakeFiles/abub.dir/build.make CMakeFiles/abub.dir/build
.PHONY : abub/fast

#=============================================================================
# Target rules for targets named bgs

# Build rule for target.
bgs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bgs
.PHONY : bgs

# fast build rule for target.
bgs/fast:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/build
.PHONY : bgs/fast

AutoBubStart.o: AutoBubStart.cpp.o
.PHONY : AutoBubStart.o

# target to build an object file
AutoBubStart.cpp.o:
	$(MAKE) -f CMakeFiles/abub.dir/build.make CMakeFiles/abub.dir/AutoBubStart.cpp.o
.PHONY : AutoBubStart.cpp.o

AutoBubStart.i: AutoBubStart.cpp.i
.PHONY : AutoBubStart.i

# target to preprocess a source file
AutoBubStart.cpp.i:
	$(MAKE) -f CMakeFiles/abub.dir/build.make CMakeFiles/abub.dir/AutoBubStart.cpp.i
.PHONY : AutoBubStart.cpp.i

AutoBubStart.s: AutoBubStart.cpp.s
.PHONY : AutoBubStart.s

# target to generate assembly for a file
AutoBubStart.cpp.s:
	$(MAKE) -f CMakeFiles/abub.dir/build.make CMakeFiles/abub.dir/AutoBubStart.cpp.s
.PHONY : AutoBubStart.cpp.s

BGS/methods/jmo/BlobExtraction.o: BGS/methods/jmo/BlobExtraction.cpp.o
.PHONY : BGS/methods/jmo/BlobExtraction.o

# target to build an object file
BGS/methods/jmo/BlobExtraction.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobExtraction.cpp.o
.PHONY : BGS/methods/jmo/BlobExtraction.cpp.o

BGS/methods/jmo/BlobExtraction.i: BGS/methods/jmo/BlobExtraction.cpp.i
.PHONY : BGS/methods/jmo/BlobExtraction.i

# target to preprocess a source file
BGS/methods/jmo/BlobExtraction.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobExtraction.cpp.i
.PHONY : BGS/methods/jmo/BlobExtraction.cpp.i

BGS/methods/jmo/BlobExtraction.s: BGS/methods/jmo/BlobExtraction.cpp.s
.PHONY : BGS/methods/jmo/BlobExtraction.s

# target to generate assembly for a file
BGS/methods/jmo/BlobExtraction.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobExtraction.cpp.s
.PHONY : BGS/methods/jmo/BlobExtraction.cpp.s

BGS/methods/jmo/BlobResult.o: BGS/methods/jmo/BlobResult.cpp.o
.PHONY : BGS/methods/jmo/BlobResult.o

# target to build an object file
BGS/methods/jmo/BlobResult.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobResult.cpp.o
.PHONY : BGS/methods/jmo/BlobResult.cpp.o

BGS/methods/jmo/BlobResult.i: BGS/methods/jmo/BlobResult.cpp.i
.PHONY : BGS/methods/jmo/BlobResult.i

# target to preprocess a source file
BGS/methods/jmo/BlobResult.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobResult.cpp.i
.PHONY : BGS/methods/jmo/BlobResult.cpp.i

BGS/methods/jmo/BlobResult.s: BGS/methods/jmo/BlobResult.cpp.s
.PHONY : BGS/methods/jmo/BlobResult.s

# target to generate assembly for a file
BGS/methods/jmo/BlobResult.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/BlobResult.cpp.s
.PHONY : BGS/methods/jmo/BlobResult.cpp.s

BGS/methods/jmo/CMultiLayerBGS.o: BGS/methods/jmo/CMultiLayerBGS.cpp.o
.PHONY : BGS/methods/jmo/CMultiLayerBGS.o

# target to build an object file
BGS/methods/jmo/CMultiLayerBGS.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/CMultiLayerBGS.cpp.o
.PHONY : BGS/methods/jmo/CMultiLayerBGS.cpp.o

BGS/methods/jmo/CMultiLayerBGS.i: BGS/methods/jmo/CMultiLayerBGS.cpp.i
.PHONY : BGS/methods/jmo/CMultiLayerBGS.i

# target to preprocess a source file
BGS/methods/jmo/CMultiLayerBGS.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/CMultiLayerBGS.cpp.i
.PHONY : BGS/methods/jmo/CMultiLayerBGS.cpp.i

BGS/methods/jmo/CMultiLayerBGS.s: BGS/methods/jmo/CMultiLayerBGS.cpp.s
.PHONY : BGS/methods/jmo/CMultiLayerBGS.s

# target to generate assembly for a file
BGS/methods/jmo/CMultiLayerBGS.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/CMultiLayerBGS.cpp.s
.PHONY : BGS/methods/jmo/CMultiLayerBGS.cpp.s

BGS/methods/jmo/LocalBinaryPattern.o: BGS/methods/jmo/LocalBinaryPattern.cpp.o
.PHONY : BGS/methods/jmo/LocalBinaryPattern.o

# target to build an object file
BGS/methods/jmo/LocalBinaryPattern.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/LocalBinaryPattern.cpp.o
.PHONY : BGS/methods/jmo/LocalBinaryPattern.cpp.o

BGS/methods/jmo/LocalBinaryPattern.i: BGS/methods/jmo/LocalBinaryPattern.cpp.i
.PHONY : BGS/methods/jmo/LocalBinaryPattern.i

# target to preprocess a source file
BGS/methods/jmo/LocalBinaryPattern.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/LocalBinaryPattern.cpp.i
.PHONY : BGS/methods/jmo/LocalBinaryPattern.cpp.i

BGS/methods/jmo/LocalBinaryPattern.s: BGS/methods/jmo/LocalBinaryPattern.cpp.s
.PHONY : BGS/methods/jmo/LocalBinaryPattern.s

# target to generate assembly for a file
BGS/methods/jmo/LocalBinaryPattern.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/LocalBinaryPattern.cpp.s
.PHONY : BGS/methods/jmo/LocalBinaryPattern.cpp.s

BGS/methods/jmo/MultiLayerBGS.o: BGS/methods/jmo/MultiLayerBGS.cpp.o
.PHONY : BGS/methods/jmo/MultiLayerBGS.o

# target to build an object file
BGS/methods/jmo/MultiLayerBGS.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/MultiLayerBGS.cpp.o
.PHONY : BGS/methods/jmo/MultiLayerBGS.cpp.o

BGS/methods/jmo/MultiLayerBGS.i: BGS/methods/jmo/MultiLayerBGS.cpp.i
.PHONY : BGS/methods/jmo/MultiLayerBGS.i

# target to preprocess a source file
BGS/methods/jmo/MultiLayerBGS.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/MultiLayerBGS.cpp.i
.PHONY : BGS/methods/jmo/MultiLayerBGS.cpp.i

BGS/methods/jmo/MultiLayerBGS.s: BGS/methods/jmo/MultiLayerBGS.cpp.s
.PHONY : BGS/methods/jmo/MultiLayerBGS.s

# target to generate assembly for a file
BGS/methods/jmo/MultiLayerBGS.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/MultiLayerBGS.cpp.s
.PHONY : BGS/methods/jmo/MultiLayerBGS.cpp.s

BGS/methods/jmo/blob.o: BGS/methods/jmo/blob.cpp.o
.PHONY : BGS/methods/jmo/blob.o

# target to build an object file
BGS/methods/jmo/blob.cpp.o:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/blob.cpp.o
.PHONY : BGS/methods/jmo/blob.cpp.o

BGS/methods/jmo/blob.i: BGS/methods/jmo/blob.cpp.i
.PHONY : BGS/methods/jmo/blob.i

# target to preprocess a source file
BGS/methods/jmo/blob.cpp.i:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/blob.cpp.i
.PHONY : BGS/methods/jmo/blob.cpp.i

BGS/methods/jmo/blob.s: BGS/methods/jmo/blob.cpp.s
.PHONY : BGS/methods/jmo/blob.s

# target to generate assembly for a file
BGS/methods/jmo/blob.cpp.s:
	$(MAKE) -f CMakeFiles/bgs.dir/build.make CMakeFiles/bgs.dir/BGS/methods/jmo/blob.cpp.s
.PHONY : BGS/methods/jmo/blob.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... abub"
	@echo "... bgs"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AutoBubStart.o"
	@echo "... AutoBubStart.i"
	@echo "... AutoBubStart.s"
	@echo "... BGS/methods/jmo/BlobExtraction.o"
	@echo "... BGS/methods/jmo/BlobExtraction.i"
	@echo "... BGS/methods/jmo/BlobExtraction.s"
	@echo "... BGS/methods/jmo/BlobResult.o"
	@echo "... BGS/methods/jmo/BlobResult.i"
	@echo "... BGS/methods/jmo/BlobResult.s"
	@echo "... BGS/methods/jmo/CMultiLayerBGS.o"
	@echo "... BGS/methods/jmo/CMultiLayerBGS.i"
	@echo "... BGS/methods/jmo/CMultiLayerBGS.s"
	@echo "... BGS/methods/jmo/LocalBinaryPattern.o"
	@echo "... BGS/methods/jmo/LocalBinaryPattern.i"
	@echo "... BGS/methods/jmo/LocalBinaryPattern.s"
	@echo "... BGS/methods/jmo/MultiLayerBGS.o"
	@echo "... BGS/methods/jmo/MultiLayerBGS.i"
	@echo "... BGS/methods/jmo/MultiLayerBGS.s"
	@echo "... BGS/methods/jmo/blob.o"
	@echo "... BGS/methods/jmo/blob.i"
	@echo "... BGS/methods/jmo/blob.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

