# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pitam/Dropbox/AutoBub3hs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pitam/Dropbox/AutoBub3hs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/AutoBub3hs/CMakeFiles /home/pitam/Dropbox/AutoBub3hs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/AutoBub3hs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AbubEntropySubsystem

# Build rule for target.
AbubEntropySubsystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AbubEntropySubsystem
.PHONY : AbubEntropySubsystem

# fast build rule for target.
AbubEntropySubsystem/fast:
	$(MAKE) -f CMakeFiles/AbubEntropySubsystem.dir/build.make CMakeFiles/AbubEntropySubsystem.dir/build
.PHONY : AbubEntropySubsystem/fast

#=============================================================================
# Target rules for targets named AbubUtility

# Build rule for target.
AbubUtility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AbubUtility
.PHONY : AbubUtility

# fast build rule for target.
AbubUtility/fast:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/build
.PHONY : AbubUtility/fast

#=============================================================================
# Target rules for targets named lbpuser

# Build rule for target.
lbpuser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lbpuser
.PHONY : lbpuser

# fast build rule for target.
lbpuser/fast:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/build
.PHONY : lbpuser/fast

#=============================================================================
# Target rules for targets named abub3hs

# Build rule for target.
abub3hs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abub3hs
.PHONY : abub3hs

# fast build rule for target.
abub3hs/fast:
	$(MAKE) -f CMakeFiles/abub3hs.dir/build.make CMakeFiles/abub3hs.dir/build
.PHONY : abub3hs/fast

AutoBubStart3.o: AutoBubStart3.cpp.o

.PHONY : AutoBubStart3.o

# target to build an object file
AutoBubStart3.cpp.o:
	$(MAKE) -f CMakeFiles/abub3hs.dir/build.make CMakeFiles/abub3hs.dir/AutoBubStart3.cpp.o
.PHONY : AutoBubStart3.cpp.o

AutoBubStart3.i: AutoBubStart3.cpp.i

.PHONY : AutoBubStart3.i

# target to preprocess a source file
AutoBubStart3.cpp.i:
	$(MAKE) -f CMakeFiles/abub3hs.dir/build.make CMakeFiles/abub3hs.dir/AutoBubStart3.cpp.i
.PHONY : AutoBubStart3.cpp.i

AutoBubStart3.s: AutoBubStart3.cpp.s

.PHONY : AutoBubStart3.s

# target to generate assembly for a file
AutoBubStart3.cpp.s:
	$(MAKE) -f CMakeFiles/abub3hs.dir/build.make CMakeFiles/abub3hs.dir/AutoBubStart3.cpp.s
.PHONY : AutoBubStart3.cpp.s

ImageEntropyMethods/ImageEntropyMethods.o: ImageEntropyMethods/ImageEntropyMethods.cpp.o

.PHONY : ImageEntropyMethods/ImageEntropyMethods.o

# target to build an object file
ImageEntropyMethods/ImageEntropyMethods.cpp.o:
	$(MAKE) -f CMakeFiles/AbubEntropySubsystem.dir/build.make CMakeFiles/AbubEntropySubsystem.dir/ImageEntropyMethods/ImageEntropyMethods.cpp.o
.PHONY : ImageEntropyMethods/ImageEntropyMethods.cpp.o

ImageEntropyMethods/ImageEntropyMethods.i: ImageEntropyMethods/ImageEntropyMethods.cpp.i

.PHONY : ImageEntropyMethods/ImageEntropyMethods.i

# target to preprocess a source file
ImageEntropyMethods/ImageEntropyMethods.cpp.i:
	$(MAKE) -f CMakeFiles/AbubEntropySubsystem.dir/build.make CMakeFiles/AbubEntropySubsystem.dir/ImageEntropyMethods/ImageEntropyMethods.cpp.i
.PHONY : ImageEntropyMethods/ImageEntropyMethods.cpp.i

ImageEntropyMethods/ImageEntropyMethods.s: ImageEntropyMethods/ImageEntropyMethods.cpp.s

.PHONY : ImageEntropyMethods/ImageEntropyMethods.s

# target to generate assembly for a file
ImageEntropyMethods/ImageEntropyMethods.cpp.s:
	$(MAKE) -f CMakeFiles/AbubEntropySubsystem.dir/build.make CMakeFiles/AbubEntropySubsystem.dir/ImageEntropyMethods/ImageEntropyMethods.cpp.s
.PHONY : ImageEntropyMethods/ImageEntropyMethods.cpp.s

LBP/LBPUser.o: LBP/LBPUser.cpp.o

.PHONY : LBP/LBPUser.o

# target to build an object file
LBP/LBPUser.cpp.o:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.o
.PHONY : LBP/LBPUser.cpp.o

LBP/LBPUser.i: LBP/LBPUser.cpp.i

.PHONY : LBP/LBPUser.i

# target to preprocess a source file
LBP/LBPUser.cpp.i:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.i
.PHONY : LBP/LBPUser.cpp.i

LBP/LBPUser.s: LBP/LBPUser.cpp.s

.PHONY : LBP/LBPUser.s

# target to generate assembly for a file
LBP/LBPUser.cpp.s:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.s
.PHONY : LBP/LBPUser.cpp.s

LBP/lbp.o: LBP/lbp.cpp.o

.PHONY : LBP/lbp.o

# target to build an object file
LBP/lbp.cpp.o:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.o
.PHONY : LBP/lbp.cpp.o

LBP/lbp.i: LBP/lbp.cpp.i

.PHONY : LBP/lbp.i

# target to preprocess a source file
LBP/lbp.cpp.i:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.i
.PHONY : LBP/lbp.cpp.i

LBP/lbp.s: LBP/lbp.cpp.s

.PHONY : LBP/lbp.s

# target to generate assembly for a file
LBP/lbp.cpp.s:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.s
.PHONY : LBP/lbp.cpp.s

ParseFolder/ParseFolder.o: ParseFolder/ParseFolder.cpp.o

.PHONY : ParseFolder/ParseFolder.o

# target to build an object file
ParseFolder/ParseFolder.cpp.o:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/ParseFolder/ParseFolder.cpp.o
.PHONY : ParseFolder/ParseFolder.cpp.o

ParseFolder/ParseFolder.i: ParseFolder/ParseFolder.cpp.i

.PHONY : ParseFolder/ParseFolder.i

# target to preprocess a source file
ParseFolder/ParseFolder.cpp.i:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/ParseFolder/ParseFolder.cpp.i
.PHONY : ParseFolder/ParseFolder.cpp.i

ParseFolder/ParseFolder.s: ParseFolder/ParseFolder.cpp.s

.PHONY : ParseFolder/ParseFolder.s

# target to generate assembly for a file
ParseFolder/ParseFolder.cpp.s:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/ParseFolder/ParseFolder.cpp.s
.PHONY : ParseFolder/ParseFolder.cpp.s

common/UtilityFunctions.o: common/UtilityFunctions.cpp.o

.PHONY : common/UtilityFunctions.o

# target to build an object file
common/UtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/common/UtilityFunctions.cpp.o
.PHONY : common/UtilityFunctions.cpp.o

common/UtilityFunctions.i: common/UtilityFunctions.cpp.i

.PHONY : common/UtilityFunctions.i

# target to preprocess a source file
common/UtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/common/UtilityFunctions.cpp.i
.PHONY : common/UtilityFunctions.cpp.i

common/UtilityFunctions.s: common/UtilityFunctions.cpp.s

.PHONY : common/UtilityFunctions.s

# target to generate assembly for a file
common/UtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/AbubUtility.dir/build.make CMakeFiles/AbubUtility.dir/common/UtilityFunctions.cpp.s
.PHONY : common/UtilityFunctions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... AbubEntropySubsystem"
	@echo "... AbubUtility"
	@echo "... rebuild_cache"
	@echo "... lbpuser"
	@echo "... abub3hs"
	@echo "... AutoBubStart3.o"
	@echo "... AutoBubStart3.i"
	@echo "... AutoBubStart3.s"
	@echo "... ImageEntropyMethods/ImageEntropyMethods.o"
	@echo "... ImageEntropyMethods/ImageEntropyMethods.i"
	@echo "... ImageEntropyMethods/ImageEntropyMethods.s"
	@echo "... LBP/LBPUser.o"
	@echo "... LBP/LBPUser.i"
	@echo "... LBP/LBPUser.s"
	@echo "... LBP/lbp.o"
	@echo "... LBP/lbp.i"
	@echo "... LBP/lbp.s"
	@echo "... ParseFolder/ParseFolder.o"
	@echo "... ParseFolder/ParseFolder.i"
	@echo "... ParseFolder/ParseFolder.s"
	@echo "... common/UtilityFunctions.o"
	@echo "... common/UtilityFunctions.i"
	@echo "... common/UtilityFunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

