# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pitam/Dropbox/AutoBub3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pitam/Dropbox/AutoBub3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/AutoBub3/CMakeFiles /home/pitam/Dropbox/AutoBub3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pitam/Dropbox/AutoBub3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abub3

# Build rule for target.
abub3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abub3
.PHONY : abub3

# fast build rule for target.
abub3/fast:
	$(MAKE) -f CMakeFiles/abub3.dir/build.make CMakeFiles/abub3.dir/build
.PHONY : abub3/fast

#=============================================================================
# Target rules for targets named lbpuser

# Build rule for target.
lbpuser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lbpuser
.PHONY : lbpuser

# fast build rule for target.
lbpuser/fast:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/build
.PHONY : lbpuser/fast

AutoBubStart3.o: AutoBubStart3.cpp.o

.PHONY : AutoBubStart3.o

# target to build an object file
AutoBubStart3.cpp.o:
	$(MAKE) -f CMakeFiles/abub3.dir/build.make CMakeFiles/abub3.dir/AutoBubStart3.cpp.o
.PHONY : AutoBubStart3.cpp.o

AutoBubStart3.i: AutoBubStart3.cpp.i

.PHONY : AutoBubStart3.i

# target to preprocess a source file
AutoBubStart3.cpp.i:
	$(MAKE) -f CMakeFiles/abub3.dir/build.make CMakeFiles/abub3.dir/AutoBubStart3.cpp.i
.PHONY : AutoBubStart3.cpp.i

AutoBubStart3.s: AutoBubStart3.cpp.s

.PHONY : AutoBubStart3.s

# target to generate assembly for a file
AutoBubStart3.cpp.s:
	$(MAKE) -f CMakeFiles/abub3.dir/build.make CMakeFiles/abub3.dir/AutoBubStart3.cpp.s
.PHONY : AutoBubStart3.cpp.s

LBP/LBPUser.o: LBP/LBPUser.cpp.o

.PHONY : LBP/LBPUser.o

# target to build an object file
LBP/LBPUser.cpp.o:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.o
.PHONY : LBP/LBPUser.cpp.o

LBP/LBPUser.i: LBP/LBPUser.cpp.i

.PHONY : LBP/LBPUser.i

# target to preprocess a source file
LBP/LBPUser.cpp.i:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.i
.PHONY : LBP/LBPUser.cpp.i

LBP/LBPUser.s: LBP/LBPUser.cpp.s

.PHONY : LBP/LBPUser.s

# target to generate assembly for a file
LBP/LBPUser.cpp.s:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/LBPUser.cpp.s
.PHONY : LBP/LBPUser.cpp.s

LBP/lbp.o: LBP/lbp.cpp.o

.PHONY : LBP/lbp.o

# target to build an object file
LBP/lbp.cpp.o:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.o
.PHONY : LBP/lbp.cpp.o

LBP/lbp.i: LBP/lbp.cpp.i

.PHONY : LBP/lbp.i

# target to preprocess a source file
LBP/lbp.cpp.i:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.i
.PHONY : LBP/lbp.cpp.i

LBP/lbp.s: LBP/lbp.cpp.s

.PHONY : LBP/lbp.s

# target to generate assembly for a file
LBP/lbp.cpp.s:
	$(MAKE) -f CMakeFiles/lbpuser.dir/build.make CMakeFiles/lbpuser.dir/LBP/lbp.cpp.s
.PHONY : LBP/lbp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... abub3"
	@echo "... lbpuser"
	@echo "... AutoBubStart3.o"
	@echo "... AutoBubStart3.i"
	@echo "... AutoBubStart3.s"
	@echo "... LBP/LBPUser.o"
	@echo "... LBP/LBPUser.i"
	@echo "... LBP/LBPUser.s"
	@echo "... LBP/lbp.o"
	@echo "... LBP/lbp.i"
	@echo "... LBP/lbp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

